from .base import *

DEBUG = False

ALLOWED_HOSTS = ["kengenal.pythonanywhere.com", "localhost"]

SECRET_KEY = os.getenv("SECRET_KEY")
CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True
SECURE_SSL_REDIRECT = True
SECURE_HSTS_SECONDS = 60
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True
